# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  claudecode-nvim = {
    pname = "claudecode-nvim";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "coder";
      repo = "claudecode.nvim";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-sOBY2y/buInf+SxLwz6uYlUouDULwebY/nmDlbFbGa8=";
    };
  };
  conjure = {
    pname = "conjure";
    version = "v4.58.0";
    src = fetchFromGitHub {
      owner = "Olical";
      repo = "conjure";
      rev = "v4.58.0";
      fetchSubmodules = false;
      sha256 = "sha256-ykJOEZXFrvCaDMdjITSTWXE5SZsZ6VU5KbYogGlpyTQ=";
    };
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "v3.15.11";
    src = fetchFromGitHub {
      owner = "obsidian-nvim";
      repo = "obsidian.nvim";
      rev = "v3.15.11";
      fetchSubmodules = false;
      sha256 = "sha256-MdM42KwPmzpXIIyGhLU1xnophmVuD+/PoMPH5+7vMYc=";
    };
  };
  vim-go = {
    pname = "vim-go";
    version = "v1.29";
    src = fetchFromGitHub {
      owner = "fatih";
      repo = "vim-go";
      rev = "v1.29";
      fetchSubmodules = false;
      sha256 = "sha256-goN/0mOExk3rPm6Z5cpnCOMM47K6lK4zBqwin1lnjgk=";
    };
  };
}
